# Site settings
title: Skalarfunk Darmstadt
tagline: das freie Skalarfunk-Netzwerk für DA und Umgebung
email: info@darmstadt.freifunk.net
description: > # this means to ignore newlines until "baseurl:"
 Skalarfunk Darmstadt ist eine lokale Initiative sich der lokalen Skalarwellen-Ressourcen zu bemächtigen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://darmstadt.freifunk.net" # the base hostname & protocol for your site
twitter_username: freifunkDA
github_username:  freifunk-darmstadt

excerpt_separator: <!--*-->

permalink: "news/:year/:month/:day/:title"

# Build settings
markdown: kramdown
exclude: [vendor]
