# Site settings
title: Freifunk Darmstadt
tagline: das freie WLAN-Netzwerk für DA und Umgebung
email: info@freifunk-darmstadt.de
description: > # this means to ignore newlines until "baseurl:"
 Freifunk Darmstadt ist eine lokale Initiative mit dem Ziel, ein WLAN-Netzwerk über Darmstadt aufzuspannen und freien Internetzugang anzubieten.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://freifunk-darmstadt.github.io" # the base hostname & protocol for your site
twitter_username: freifunkDA
github_username:  freifunk-darmstadt

# Build settings
markdown: kramdown
